### ISSUE TITLE
Attempted to get trait from destroyed object (boris 2214 (not in world))

### ISSUE THREAD

**Issue by zgrsgr** [cookgreen/Yuris-Revenge#115]
Unknown issue.

**Comment by mmtrt** [comment]
I had this same issue today game crashed I'm using custom map made for 12 players.

```
OpenRA engine version release-20200202
Red Alert 2 Yuri's Revenge mod version release-20200202
on map 06da53d36cbf07cffad11a590132d2a031015b5a (Tour of Eygpt Gold (NC) V1 by MMTRT).
Date: 2020-04-07 04:15:50Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.InvalidOperationException`: Attempted to get trait from destroyed object (boris 1040 (not in world))
   at OpenRA.TraitDictionary.CheckDestroyed(Actor actor)
   at OpenRA.TraitDictionary.Get[T](Actor actor)
   at OpenRA.Mods.YR.Activities.MarkerSlaveLeave.<>c__DisplayClass3_0.<Tick>b__0(World w)
   at OpenRA.World.Tick()
   at OpenRA.Game.InnerLogicTick(OrderManager orderManager)
   at OpenRA.Game.LogicTick()
   at OpenRA.Game.Loop()
   at OpenRA.Game.Run()
   at OpenRA.Game.InitializeAndRun(String[] args)
   at OpenRA.WindowsLauncher.RunGame(String[] args)
```
