### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by cookgreen** [cookgreen/Yuris-Revenge#131]
C:\Program Files (x86)\OpenRAYR>OpenRA.Server.exe Game.Mod=yr Server.Name="Abarr
at's Abode - YR" Server.ListenPort=27015 Server.AdvertiseOnline=True Server.Enab
leSingleplayer=False Server.Password="" Server.GeoIPDatabase="" Server.RequireAu
thentication=False Server.ProfileIDBlacklist="" Server.ProfileIDWhitelist="" Ser
ver.EnableSyncReports=False Server.ShareAnonymizedIPs=True
[2020-04-12T22:04:34] Starting dedicated server for mod: yr

Unhandled Exception: System.NotSupportedException: An attempt was made to load a
n assembly from a network location which would have caused the assembly to be sa
ndboxed in previous versions of the .NET Framework. This release of the .NET Fra
mework does not enable CAS policy by default, so this load may be dangerous. If
this load is not intended to sandbox the assembly, please enable the loadFromRem
oteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more in
formation.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence
)
   at System.Reflection.Assembly.LoadFile(String path)
   at OpenRA.ObjectCreator..ctor(Manifest manifest, InstalledMods mods)
   at OpenRA.ModData..ctor(Manifest mod, InstalledMods mods, Boolean useLoadScre
en)
   at OpenRA.Server.Program.Main(String[] args)

OS: Windows x64

**Comment by cookgreen** [comment]
Server Hoster already Fixed
